<a href="https://colab.research.google.com/github/jihyeon602/Statics-Machine_Learning/blob/main/%EB%A0%88%EC%9D%B4%EB%B8%94%EC%9D%B8%EC%BD%94%EB%94%A9%2C_%EC%9B%90%ED%95%AB%EC%9D%B8%EC%BD%94%EB%94%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','믹서','믹서']

encoder = LabelEncoder() # 객체 생성
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 2 2]


In [ ]:
print('인코딩 클래스:', encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [ ]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','믹서','믹서']
items = np.array(items).reshape(-1, 1)
#print(items) #7x1 행렬

oh_encoder = OneHotEncoder() # 객체 생성
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print(oh_labels, type(oh_labels))
print('원핫인코딩 데이터')
print(oh_labels.toarray()) # 희소행렬 -> 밀집행렬
print('-' * 50)
print('원핫인코딩 데이터 차원')
print(oh_labels.shape)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 5)	1.0
  (4, 3)	1.0
  (5, 2)	1.0
  (6, 2)	1.0 <class 'scipy.sparse._csr.csr_matrix'>
원핫인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
--------------------------------------------------
원핫인코딩 데이터 차원
(7, 6)


In [ ]:
import pandas as pd
df = pd.DataFrame({'item' : ['TV', '냉장고', '전자레인지', '컴퓨터', '선풍기','믹서','믹서']})
pd.get_dummies(df)
#

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0     True     False    False     False       False     False
1    False      True    False     False       False     False
2    False     False    False     False        True     False
3    False     False    False     False       False      True
4    False     False    False      True       False     False
5    False     False     True     False       False     False
6    False     False     True     False       False     False